[package]
name = "ytrss"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
reqwest = "0.12.18"
tokio = { version = "1.45.1", features = ["full"] }
select = "0.6.1"
thiserror = "2.0.12"
url = "2.5.4"
futures = "0.3.31"
